### ISSUE TITLE
só uma parte dos posts ou o post inteiro?

### ISSUE THREAD

**Issue by dfalbel** [dfalbel/brbloggers#1]
* por enquanto só aparece uma parte do post, por questões técnicas..

**Comment by jtrecenti** [comment]
é possível aumentar o número de caracteres máximo?

**Comment by dfalbel** [comment]
Acho que dá, vou adicionar um parâmetro pra isso

**Comment by dfalbel** [comment]
agora é só alterar o parametro `maxChars` no `config.toml`
