### ISSUE TITLE
Parou de funcionar?

### ISSUE THREAD

**Issue by sillasgonzaga** [dfalbel/brbloggers#11]
Talvez vocês já estejam cientes, mas entrei agora no site e a última atualização é de 18/09.

Falando por experiência própria da vez em que montei o Rbloggers-BR no Twitter, é comum o código não funcionar em posts novos que apresentam determinadas características. Algo que poderia ter me ajudado a perceber esses problemas antes teria sido implementar um código que me enviasse um e-mail quando o extrator de posts retornasse um erro.

**Comment by dfalbel** [comment]
eu vi que parou de funcionar faz um tempo, mas infelizmente estou sem tempo para manter :(
eu acho que ele ainda está capturando os posts corretamente, mas não está conseguindo renderizar.

**Comment by dfalbel** [comment]
@sillasgonzaga só agora tive tempo p/ arrumar! acho que agora está correto de novo!
