### ISSUE TITLE
Desejo incluir meu blog no https://brbloggers.com.br/

### ISSUE THREAD

**Issue by gomesfellipe** [dfalbel/brbloggers#12]
Boa tarde,
meu nome é Fellipe, sou entusiasta pela ciencia de dados e apaixonado por programar em R,  notei a carência e a dificuldade que cientistas de dados enfrentam ao compartilhar e demonstrar o que podemos fazer (ainda mais com materiais em português) com tantos recursos computacionais e estatísticos que tomei a iniciativa de criar um blog, gostaria de inclui-lo na página https://brbloggers.com.br/ pois além de admirar muito o trabalho que acompanho no http://curso-r.com/, acredito que eu possa contribuir de alguma forma e ser útil para toda a comunidade q já me ajudou tanto

link do blog:

gomesfellipe.github.io

**Comment by dfalbel** [comment]
Oi Felipe,

Muito obrigado! A motivação é exatamente essa! 
Muito legal o seu blog também!!

Nos últimos tempos tive pouco tempo para cuidar do brbloggers. A partir de fevereiro estarei mais tranquilo e poderei me dedicar mais para manter-lo. Sendo assim, incluirei o seu blog na lista ~ no início de fevereiro, ok?

Abraços,
Daniel

**Comment by gomesfellipe** [comment]
Maravilha! Vou aguardar

**Comment by dfalbel** [comment]
@gomesfellipe Está lá!! Se puder dê uma olhada para ver se foi tudo direitinho!

**Comment by gomesfellipe** [comment]
Muito obrigado Daniel! Parece q vc adivinhou q eu tinha um post prontinho pra lançar hoje hehehhe

So um pequenino detalhe: nas tags meu nome ta como "Felippe-gomes" enquanto meu nome é "Fellipe-gomes" hahahha

Esse eh o mal do meu nome sao muitos jeitos de escrever mas mesmo assim ja adorei, vou colocar o link do brbloggers e do curso-r no meu blog como parceiros tbm pode ser?

Desde ja agradecido, forte abraço!

Enviado do meu iPhone

Em 12 de jan de 2018, às 09:45, Daniel Falbel <notifications@github.com<mailto:notifications@github.com>> escreveu:


Closed #12<https://github.com/brbloggers/brbloggers/issues/12>.

**Comment by dfalbel** [comment]
Ops! vou arrumar logo menos!

Pode claro!!

**Comment by dfalbel** [comment]
agora sim! corrigido!
