### ISSUE TITLE
Dúvida sobre conteúdo

### ISSUE THREAD

**Issue by gustavobio** [dfalbel/brbloggers#14]
Boa noite,

Eu tenho uma página no medium - https://medium.com/@ghcarvalho/latest - em que posto sobre dados que eu acho interessantes. Algumas postagens são mais centradas no R, mas a maioria são sobre os dados mesmo. Mesmo assim, eu disponibilizo todos os scripts pra reproduzir os posts. Fiquei em dúvida se esse tipo de coisa entra no escopo do brbloggers. Entra?

Abraços,

Gustavo.

**Comment by gustavobio** [comment]
Pra ilustrar, tem esse tipo de postagem, com códigos:

https://medium.com/@ghcarvalho/explorando-os-dados-de-criminalidade-em-são-paulo-479fa6943096
https://medium.com/@ghcarvalho/como-corrigir-nomes-e-buscar-informações-taxonômicas-de-plantas-no-r-cdd019d5de8f
https://medium.com/@ghcarvalho/as-cores-das-flores-16b98a333a33

E esse tipo, sem código no post mas tudo no github:
https://medium.com/@ghcarvalho/presidenciáveis-no-twitter-5fa2a7ec144b
https://medium.com/@ghcarvalho/são-paulo-tem-verões-cada-vez-mais-quentes-6821d4f3ec05
https://medium.com/@ghcarvalho/como-vota-deputado-67e5e60596e1
https://medium.com/@ghcarvalho/os-nomes-da-moda-ontem-e-hoje-f0bdc508efef

**Comment by dfalbel** [comment]
Olá Gustavo! Com certeza entra! Muito legal!
Vou incluir a sua página em breve!

Abraços!

**Comment by dfalbel** [comment]
@gustavobio Está lá! https://brbloggers.com.br/ghcarvalho 
Pode dar uma olhada e ver se está tudo certo?

Abraços,
Daniel

**Comment by gustavobio** [comment]
@dfalbel, tudo certo, obrigado!

Abraços
