### ISSUE TITLE
Adição de novo blog

### ISSUE THREAD

**Issue by clente** [dfalbel/brbloggers#4]
Olá, gostaria de adicionar o meu blog ao bRbloggers.

Nome: Mind & Iron
Home: [http://ctlente.com/pt/home](http://ctlente.com/pt/home)
Posts: [http://ctlente.com/pt/](http://ctlente.com/pt/)
RSS: [http://ctlente.com/pt/index.xml](http://ctlente.com/pt/index.xml)

**Comment by dfalbel** [comment]
Coloquei com esse commit: 6c667b841f15e9619db18619458bdf589c9400b7 ! Dá uma olhada pra ver se está tudo certo!

**Comment by clente** [comment]
Está tudo em ordem! Obrigado!
