### ISSUE TITLE
Links no RSS não funcionam

### ISSUE THREAD

**Issue by lucianosb** [dfalbel/brbloggers#8]
Estou inscrito no RSS pelo leitor built-in do Opera e os links do bR Blogggers sao os únicos que não levam pra lugar nenhum, eu clico e continuo na mesma página do navegador.

Será bug no feed ou no Opera?

**Comment by dfalbel** [comment]
@lucianosb Desculpa a demora para responder! Vou dar uma olhada nisso. Em tempo, você se inscreveu neste feed? https://brbloggers.com.br/index.xml

Abraços,
Daniel

**Comment by lucianosb** [comment]
Foi exatamente essa URL @dfalbel. Foi a URL detectada pelo sistema de notícias do Opera 47.

Grato por colaborar.
